

data_dir = '/Users/philipmassey/PycharmProjects/stock_market/market_data/data'


#FOLDERS
all = 'ALL'
ark = 'ARK'
etf = 'ETF'
holding = 'Holding'
sa = 'Seeking_Alpha'
test = 'test'
watching = 'Watching'
db_client = 'stock_market'
db_close = 'market_data_close'
db_volume = 'market_data_volume'
db_etf_close = 'etf_close'
db_etf_vol = 'etf_vol'

from .csv_data_defs import *
from .portfolio_defs import *
from .stock_mdb import *
from .exchange_api import *


ark = 'ARK'
arkf = 'ARKF'
arkg = 'ARKG'
arkk = 'ARKK'
arkq = 'ARKQ'
arkw = 'ARKW'
arkx = 'ARKX'
additive_manufacturing = 'Additive Manufacturing'
alternative_medicine = 'Alternative Medicine'
biotechnology_gnom = 'Biotechnology GNOM'
cloud_enterprise_apps = 'Cloud Enterprise Apps'
comm_services = 'Comm Services'
comm_services___comm_equip = 'Comm Services - Comm Equip'
consumer_disc = 'Consumer Disc'
consumer_disc___auto_parts_and_equipment = 'Consumer Disc - Auto Parts and Equipment'
consumer_disc___homebuilding = 'Consumer Disc - Homebuilding'
consumer_disc_auto_manu = 'Consumer Disc-Auto Manu'
consumer_disc_home_building = 'Consumer Disc-Home Building'
consumer_disc_home_furnish_retail = 'Consumer Disc-Home Furnish & Retail'
consumer_disc_internet_direct = 'Consumer Disc-Internet & Direct'
consumer_staples = 'Consumer Staples'
dia = 'DIA'
dividends = 'Dividends'
electic_vehicle_2 = 'Electic Vehicle 2'
electric_vehicle = 'Electric Vehicle'
electriv_vehicle_china = 'Electriv Vehicle China'
financials = 'FinancIals'
health_care = 'Health Care'
health_care___biotechnology = 'Health Care - Biotechnology'
health_care___growth = 'Health Care - Growth'
health_care___life_sciences_tools_and_services = 'Health Care - Life Sciences Tools and Services'
health_care___momentum = 'Health Care - Momentum'
health_care___pharmaceuticals = 'Health Care - Pharmaceuticals'
health_care___wall_st = 'Health Care - Wall St'
health_care_pharmaceuticals_momentum = 'Health Care-Pharmaceuticals Momentum'
heatlth_care_alternative_medicine = 'Heatlth Care-Alternative Medicine'
industrials = 'Industrials'
industrials___building_products = 'Industrials - Building Products'
industrials___container_ships = 'Industrials - Container Ships'
industrials___dry_buik = 'Industrials - Dry Buik'
industrials___electrical_components_and_equipment = 'Industrials - Electrical Components and Equipment'
industrials___marine = 'Industrials - Marine'
industrials___trading_companies_and_distributors = 'Industrials - Trading Companies and Distributors'
industrials_trucking = 'Industrials-Trucking'
industrials_value = 'Industrials-Value'
inf_tech = 'Inf Tech'
inf_tech___application_software = 'Inf Tech - Application Software'
inf_tech___internet_services_infrastructure = 'Inf Tech - Internet Services & Infrastructure'
inf_tech___profitability = 'Inf Tech - Profitability'
inf_tech___semiconductor_equip = 'Inf Tech - Semiconductor Equip'
inf_tech___semiconductors = 'Inf Tech - Semiconductors'
inf_tech___systems_software = 'Inf Tech - Systems Software'
inf_tech___value = 'Inf Tech - Value'
markets_etf = 'Markets ETF'
materials = 'Materials'
materials___steel = 'Materials - Steel'
materials_lumber = 'Materials-Lumber'
materials_steel = 'Materials-Steel'
real_estate___retail_reits = 'Real Estate - Retail REITs'
real_estate_services = 'Real Estate Services'
robinhood = 'Robinhood'
sector_xl_etf = 'Sector XL ETF'
stock_market_asia = 'Stock Market Asia'
stock_market_emerging = 'Stock Market Emerging'
stock_market_europe = 'Stock Market Europe'
thematic_etf = 'Thematic ETF'
test_symbols = 'Test_symbols'
top_growth_stocks = 'Top Growth Stocks'
top_reits = 'Top REITs'
top_rated_dividend_stocks = 'Top Rated Dividend Stocks'
top_rated_stocks = 'Top Rated Stocks'
top_small_cap_stocks = 'Top Small Cap Stocks'
top_stocks_by_quant = 'Top Stocks by Quant'
top_stocks_in_renewable_electricity = 'Top Stocks in Renewable Electricity'
top_value_stocks = 'Top Value Stocks'
utilities = 'Utilities'
utilities_renewable_energy = 'Utilities-Renewable Energy'
water_etf = 'Water ETF'
